title: 'Manage Problems'
modelClass: Bree7e\Cris\Models\Publication
list: $/bree7e/cris/models/publication/columns_problems.yaml
recordUrl: 'bree7e/cris/publications/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
