# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  index:
      pageSize: 20
  store:
  show:
  update:
  destroy:

# Model Class name
modelClass: Bree7e\Cris\Models\Publication
