# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  index:
      pageSize: 5

modelClass: Bree7e\Cris\Models\Publication
