# ===================================
#  Relation Behavior Config
# ===================================

publications:
    label: Публикации
    view:
        list: $/bree7e/cris/models/publication/columns_list.yaml
        toolbarButtons: create|add|remove
    manage:        
        form: $/bree7e/cris/models/publication/fields_simple.yaml
        showSearch: true
        recordsPerPage: 10